### ISSUE TITLE
Attendance (Halaman Admin)

### ISSUE THREAD

**Issue by bening14** [solusi-cipta-media/masterhrsale#1]
![image](https://user-images.githubusercontent.com/55275901/125158486-bc48cc00-e19b-11eb-811f-3f0c4f3ec2ba.png)

1. Laporan Attendance , ditambah Lokasi Check IN dan Check Out
2. Informasi berbentuk koordinat (Lg LT)
3. Jika informasi kordinat di klik akan open new tab google Maps dengan pin lokasi karyawan

**Comment by nggepe** [comment]
yang ini juga sudah pak @bening14 ?

**Comment by bening14** [comment]
Ini sudah mas, issuenya tambah lokasi pencarian
