### ISSUE TITLE
Report Admin (Attendance)

### ISSUE THREAD

**Issue by bening14** [solusi-cipta-media/masterhrsale#2]
![image](https://user-images.githubusercontent.com/55275901/125158570-3c6f3180-e19c-11eb-95ff-c64a1f99d46b.png)

![image](https://user-images.githubusercontent.com/55275901/125158595-5872d300-e19c-11eb-80ff-9a0ad3075d44.png)

PIlih Laporan Kehadiran

![image](https://user-images.githubusercontent.com/55275901/125159299-c9b48500-e1a0-11eb-84fc-930eaf4da2fb.png)

1. Tabel informasi kehadiran ditambah lokasi check in, lokasi check out, terlambat, meninggalkan dini, lembur

**Comment by nggepe** [comment]
@bening14 pak, yang ini sudah ya kemaren?

**Comment by bening14** [comment]
Sudah mas, issue nya tambah pencarian untuk all karyawan

**Comment by nggepe** [comment]
saya close ya pak
