### ISSUE TITLE
Attendance Report Enhancement

### ISSUE THREAD

**Issue by nggepe** [solusi-cipta-media/masterhrsale#3]
HRSALE. Halaman attendance Report ini ditambahi pencarian tapi nggak usah ada choose an Employee , jadi bisa tarik semua data

![image](https://user-images.githubusercontent.com/20833635/127244858-a31a3b03-d667-4c76-a27a-6c57bb4e26ff.png)

**Comment by bening14** [comment]
Iya betul, ini mas

**Comment by nggepe** [comment]
iya pak. ini saya bedah dulu. ☺

**Comment by arthurjulio** [comment]
Ada 2 opsi sih mas, tapi coba dicek aja dulu yang mana yang lebih mudah diimplementasikan
1. Pilihan employee nya dihapus
2. Ditambahkan pilihan "All"

**Comment by nggepe** [comment]
> Ada 2 opsi sih mas, tapi coba dicek aja dulu yang mana yang lebih mudah diimplementasikan
> 
> 1. Pilihan employee nya dihapus
> 2. Ditambahkan pilihan "All"

iyo thur, tapi iki koyok e mayak kodingane. wkwkkw
1. reports_employee_attendance.js
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/skin/hrsale_assets/hrsale_scripts/reports_employee_attendance.js#L52
ketika form submit emang bener ngelempar data id pegawai karo company.
iki url submit e.
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/skin/hrsale_assets/hrsale_scripts/reports_employee_attendance.js#L61
dia mengambil data ndek controller `report` method `employee_date_wise_list()`
2. report.php
iki method `employee_date_wise_list()`
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L907
tapi masalahe, ndek method iki, cara ngambil informasi tentang pegawai iku wes tumplek blek dadi siji. ndek variable `$employee`
iki pengambilan `$employee_id` sing dikirim teko datatable request
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L923
terus iki njupuk informasi user by id
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L926
dan masalahe ndek semua bagian seng bersangkut paut karo variable `$employee` iku mek njupuk 1 row, soale kan dia mengambil nggawe id.
iki beberapa line of code sing njupuk variable `$employee`
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L948
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1010
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1013
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1018
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1034
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1064
media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1118
media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1121
media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1162
media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1167
media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1175
media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1218
media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1220

iku kabeh bersangkut paut karo request `id_user` sing teko datatable, dadi ketika `id_user` dikosongi. otomatis gak iso njupuk kabeh informasi tentang iku. tapi lek misal aku select all ngko teko table engko akhire sing ngisor-ngisor malih error soale, gak iso multiple. dia gak gawe query join sing iso meringkas data.

solusine piye yo?

**Comment by arthurjulio** [comment]
Lek misalkan dibawah line iki
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L923

dikeki kondisi `if get("user_id") = "all"`
nambah kondisi baru, yang lama dimasukkan ke `else`, jadi enggak perlu merubah method yang sudah ada 

mungkin enggak itu mas?

**Comment by nggepe** [comment]
> Lek misalkan dibawah line iki
> https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L923
> 
> dikeki kondisi `if get("user_id") = "all"`
> nambah kondisi baru, yang lama dimasukkan ke `else`, jadi enggak perlu merubah method yang sudah ada
> 
> mungkin enggak itu mas?

masalahe akeh variable sing kudu njupuk `$employee` berdasarkan id
iki lo thur

https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L948
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1010
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1013
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1018
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1034
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1064
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1118
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1121
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1162
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1167
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1175
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1218
https://github.com/solusi-cipta-media/masterhrsale/blob/72119d8ae12310b75d79c748ea75543ad01016a7/hrsale/application/controllers/admin/Reports.php#L1220

**Comment by nggepe** [comment]
1. `$office_shift`
2. `$check`
3. `$attendance`
4. `$clkInIp`
5. `$total_hrs`
6. `$total_rest`
7. `$leave_date_chck`
8. `$leave_date`
9. `$check_out`
10. `$first_out`
11. `$clkOutIp`
12. `$full_name`
13. `$company`
